// <autogenerated />
#nullable enable
using System.IO.Compression;
using ProtoBuf;

namespace SecretLabDependenciesBuilder.Downloader
{
    [ProtoContract]
    class DepotConfigStore
    {
        [ProtoMember(1)]
        public Dictionary<uint, ulong> InstalledManifestIDs { get; private set; }

        string? _fileName;

        DepotConfigStore()
        {
            InstalledManifestIDs = new Dictionary<uint, ulong>();
        }

        static bool Loaded
        {
            get { return Instance != null; }
        }

        public static DepotConfigStore? Instance;

        public static void LoadFromFile(string filename)
        {
            if (Loaded)
                throw new Exception("Config already loaded");

            if (File.Exists(filename))
            {
                using (var fs = File.Open(filename, FileMode.Open))
                using (var ds = new DeflateStream(fs, CompressionMode.Decompress))
                    Instance = Serializer.Deserialize<DepotConfigStore>(ds);
            }
            else
            {
                Instance = new DepotConfigStore();
            }

            Instance._fileName = filename;
        }

        public static void Save()
        {
            if (!Loaded)
                throw new Exception("Saved config before loading");
            
            if (Instance!._fileName == null)
                throw new Exception("Saved config before setting filename");

            using (var fs = File.Open(Instance._fileName, FileMode.Create))
            using (var ds = new DeflateStream(fs, CompressionMode.Compress))
                Serializer.Serialize(ds, Instance);
        }
    }
}
